package entities;
// Generated Aug 24, 2017 3:30:49 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Drug generated by hbm2java
 */
@Entity
@Table(name = "Drug", catalog = "QuanLyThuoc")
public class Drug implements java.io.Serializable {

	private String drugId;
	private String drugName;
	private String drugContent;
	private String drugUnit;
	private String drugIngredients;
	private String guide;
	private Date timeExpired;
	private BigDecimal priceNr;
	private BigDecimal priceHr;
	private int quantity;
	private String manufacturer;
	private Set<InvoiceDetails> invoiceDetailses = new HashSet<InvoiceDetails>(0);

	public Drug() {
	}

	public Drug(String drugId, String drugName, String drugContent, String drugUnit, String drugIngredients,
			String guide, Date timeExpired, BigDecimal priceNr, BigDecimal priceHr, int quantity,
			String manufacturer) {
		this.drugId = drugId;
		this.drugName = drugName;
		this.drugContent = drugContent;
		this.drugUnit = drugUnit;
		this.drugIngredients = drugIngredients;
		this.guide = guide;
		this.timeExpired = timeExpired;
		this.priceNr = priceNr;
		this.priceHr = priceHr;
		this.quantity = quantity;
		this.manufacturer = manufacturer;
	}

	public Drug(String drugId, String drugName, String drugContent, String drugUnit, String drugIngredients,
			String guide, Date timeExpired, BigDecimal priceNr, BigDecimal priceHr, int quantity,
			String manufacturer, Set<InvoiceDetails> invoiceDetailses) {
		this.drugId = drugId;
		this.drugName = drugName;
		this.drugContent = drugContent;
		this.drugUnit = drugUnit;
		this.drugIngredients = drugIngredients;
		this.guide = guide;
		this.timeExpired = timeExpired;
		this.priceNr = priceNr;
		this.priceHr = priceHr;
		this.quantity = quantity;
		this.manufacturer = manufacturer;
		this.invoiceDetailses = invoiceDetailses;
	}

	@Id

	@Column(name = "DRUG_ID", unique = true, nullable = false, length = 10)
	public String getDrugId() {
		return this.drugId;
	}

	public void setDrugId(String drugId) {
		this.drugId = drugId;
	}

	@Column(name = "DRUG_NAME", nullable = false)
	public String getDrugName() {
		return this.drugName;
	}

	public void setDrugName(String drugName) {
		this.drugName = drugName;
	}

	@Column(name = "DRUG_CONTENT", nullable = false, length = 50)
	public String getDrugContent() {
		return this.drugContent;
	}

	public void setDrugContent(String drugContent) {
		this.drugContent = drugContent;
	}

	@Column(name = "DRUG_UNIT", nullable = false)
	public String getDrugUnit() {
		return this.drugUnit;
	}

	public void setDrugUnit(String drugUnit) {
		this.drugUnit = drugUnit;
	}

	@Column(name = "DRUG_INGREDIENTS", nullable = false, length = 250)
	public String getDrugIngredients() {
		return this.drugIngredients;
	}

	public void setDrugIngredients(String drugIngredients) {
		this.drugIngredients = drugIngredients;
	}

	@Column(name = "GUIDE", nullable = false)
	public String getGuide() {
		return this.guide;
	}

	public void setGuide(String guide) {
		this.guide = guide;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIME_EXPIRED", nullable = false, length = 23)
	public Date getTimeExpired() {
		return this.timeExpired;
	}

	public void setTimeExpired(Date timeExpired) {
		this.timeExpired = timeExpired;
	}

	@Column(name = "PRICE_NR", nullable = false, scale = 4)
	public BigDecimal getPriceNr() {
		return this.priceNr;
	}

	public void setPriceNr(BigDecimal priceNr) {
		this.priceNr = priceNr;
	}

	@Column(name = "PRICE_HR", nullable = false, scale = 4)
	public BigDecimal getPriceHr() {
		return this.priceHr;
	}

	public void setPriceHr(BigDecimal priceHr) {
		this.priceHr = priceHr;
	}

	@Column(name = "QUANTITY", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "MANUFACTURER", nullable = false, length = 50)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drug")
	public Set<InvoiceDetails> getInvoiceDetailses() {
		return this.invoiceDetailses;
	}

	public void setInvoiceDetailses(Set<InvoiceDetails> invoiceDetailses) {
		this.invoiceDetailses = invoiceDetailses;
	}

}
