package entities;
// Generated Aug 27, 2017 1:16:50 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * InvoiceDetails generated by hbm2java
 */
@Entity
@Table(name = "Invoice_details", catalog = "QuanLyThuoc")
public class InvoiceDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String invId;
	private String drugId;
	private Drug drug;
	private Invoices invoices;
	private Integer numberDetail;
	private BigDecimal price;

	public InvoiceDetails() {
	}

	public InvoiceDetails(Drug drug, Invoices invoices) {
		this.drug = drug;
		this.invoices = invoices;
	}

	public InvoiceDetails(Drug drug, Invoices invoices, Integer numberDetail, BigDecimal price) {
		this.drug = drug;
		this.invoices = invoices;
		this.numberDetail = numberDetail;
		this.price = price;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "invoices"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "Inv_id", unique = true, nullable = false, length = 10)
	public String getInvId() {
		return this.invId;
	}

	public void setInvId(String invId) {
		this.invId = invId;
	}
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "drug"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "Drug_id", unique = true, nullable = false, length = 10)
	public String getDrugId() {
		return drugId;
	}

	public void setDrugId(String drugId) {
		this.drugId = drugId;
	}
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Drug getDrug() {
		return this.drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Invoices getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Invoices invoices) {
		this.invoices = invoices;
	}

	@Column(name = "Number_detail")
	public Integer getNumberDetail() {
		return this.numberDetail;
	}

	public void setNumberDetail(Integer numberDetail) {
		this.numberDetail = numberDetail;
	}

	@Column(name = "Price", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	
	private BigDecimal xxx;
	public void setXxx(BigDecimal xxx) {
		this.xxx = xxx;
	}

	public BigDecimal getXxx(){
		BigDecimal a = BigDecimal.valueOf(this.numberDetail);
		BigDecimal b = this.price;
		BigDecimal c = b.multiply(a);
		return c;
	}
	
	
	

}
